mail:
  receivers:
  - 12345@qq.com
  - 54321@qq.com
  sender:
    address: 12345@163.com
    host: smtp.163.com
    password: xiaoheizi
    port: 465
    user: zhiyinnitaimei
  sent:
  - '2022-10-26'
plan:
- mail: 12345@qq.com
  openid: abcd
  success: false
  time:
    '2022-11-02':
    - 11:00-11:30
    - 13:30-14:00
    '2022-11-03':
    - 9:00-9:30
    - 9:30-10:00
- mail: 54321@qq.com
  openid: gggg
  success: false
  time:
  - '2022-11-02':
    - 11:00-11:30
    - 13:30-14:00
  - '2022-11-03':
    - 9:00-9:30
    - 9:30-10:00
